eno=int(input("Enter the number:"))
ename=(input("Enter the name:"))
esalary=float(input("enter the salary:"))
eaddres=(input("Enter the address:"))
emari=bool(input("Marital status:"))
print("emp ID:",eno)
print("emp name:",ename)
print("emp salary:",esalary)
print("emp address:",eaddres)
print("emp marital status:",emari)
